version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    environment:
      - PORT=8080
    ports:
      - "5858:5858"
      - "8080:8080"
    volumes:
      - ../src:/app/
